name = "sync-worker"
main = "src/index.ts"
compatibility_date = "2024-05-12"

# [vars]
# API_FOOTBALL_TOKEN = "dummy_token_for_api_football"

[triggers]
crons = ["*/30 * * * *"] # Every 1 minutes

[[kv_namespaces]]
binding = "DATA_KV"
id = "7919e7ed95e74de28b311de524a4cc7b"

[[d1_databases]]
binding = "DB"
database_name = "prode_u_db"
database_id = "86abbf22-7a40-4336-8419-facbac2ae0dd"