name = "api-worker"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[vars]
JWT_SECRET = "prode_u_super_secret_key_for_jwt_auth_mundial_2026"

[[d1_databases]]
binding = "DB"
database_name = "prode_u_db"
database_id = "86abbf22-7a40-4336-8419-facbac2ae0dd"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "prode-u-images"

[[kv_namespaces]]
binding = "DATA_KV"
id = "7919e7ed95e74de28b311de524a4cc7b"

